spring:
  datasource:
    druid:
      initial-size: 16
      min-idle: 16
      max-active: 32
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: root

#  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 2000
    database: 0

my-framework:
  name: ry
  nickName: 任洋爱吃肉