spring:
  datasource:
    druid:
      initial-size: 16
      min-idle: 16
      max-active: 32
#      url: jdbc:mysql://172.16.0.27:3306/foodie
      url: jdbc:mysql://192.168.31.27:3306/foodie
      username: root
      password: 199426