server:
  port: 8080
  shutdown: graceful    # 开启优雅停止 Web 容器，默认为 IMMEDIATE：立即停止

spring:
  application:
    name: my-framework
  profiles:
    active: dev
  lifecycle:
    timeout-per-shutdown-phase: 30s     # 最大等待时间

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
  mapper-locations: classpath:mapper/**/*.xml

pagehelper:
  auto-dialect: true

logging:
  level:
    com.ry.mapper: debug

# 开启后可以打印自动配置报告
#debug: true
