spring:
  datasource:
    druid:
      initial-size: 16
      min-idle: 16
      max-active: 32
      url: jdbc:mysql://172.16.0.27:3306/foodie
      username: root
      password: 199426

  redis:
    host: 172.16.0.27
    port: 6379
    timeout: 2000
    database: 0

my-framework:
  name: ry
  nickName: 任洋爱吃肉