server:
  port: 8088
  shutdown: graceful    # 开启优雅停止 Web 容器，默认为 IMMEDIATE：立即停止

spring:
  application:
    name: my-framework
  profiles:
    active: all,dev
  lifecycle:
    timeout-per-shutdown-phase: 30s     # 最大等待时间

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml

pagehelper:
  auto-dialect: true




